//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RoboticController.rc
//
#define ID_ITEMOPCION00                 1
#define ID_ITEMOPCION01                 2
#define ID_ITEMOPCION02                 3
#define ID_ITEMOPCION03                 4
#define ID_ITEMOPCION04                 5
#define ID_ITEMOPCION05                 6
#define ID_ITEMOPCION06                 7
#define ID_ITEMOPCION07                 8
#define ID_ITEMOPCION08                 9
#define IDB_EMERGENCY_STOP              119
#define IDB_ORIGEN                      120
#define IDB_NEST                        121
#define IDB_SET                         124
#define IDB_FORWARD                     125
#define IDB_BACK                        126
#define IDB_INITIALIZE                  127
#define IDB_RESET                       128
#define IDB_TRAJ                        129
#define IDB_TECHBOX                     130
#define IDB_OPENGRIPPER                 131
#define IDB_CLOSEGRIPPER                132
#define IDB_TEST_BACH                   133
#define IDB_ACEPTAR                     134
#define IDB_AJUSTE                      135
#define IDB_ALARMA                      136
#define IDB_GRAFICA                     137
#define IDB_GET                         138
#define MENU_TXT                        142
#define IDB_Wicon                       143
#define IDC_EDIT1                       1033
#define IDC_COMBO_TAREA_RTC             1042
#define IDC_EVELO                       1051
#define IDC_EVELO2                      1052
#define IDC_EVELO3                      1053
#define IDC_EVELO4                      1054
#define IDC_EVELO5                      1055
#define IDC_PUNTOSUSER                  1061
#define IDC_PUNTOSDIS                   1062
#define IDC_GRIOPEN                     1100
#define IDC_GRICLOSE                    1101
#define IDC_NEST                        1103
#define IDC_ORIGEN                      1104
#define IDC_EPOS                        1108
#define IDC_EACE                        1109
#define IDC_EACE2                       1110
#define IDC_EPOS2                       1111
#define IDC_EPOS3                       1113
#define IDC_EACE3                       1114
#define IDC_RHOMBRO                     1115
#define IDC_RCINTURA                    1116
#define IDC_RCODO                       1117
#define IDC_RPITCH                      1118
#define IDC_RROLL                       1119
#define IDC_EPOS4                       1121
#define IDC_EACE4                       1122
#define IDC_EPOS5                       1124
#define IDC_EACE5                       1125
#define IDC_BACK                        1129
#define IDC_BENVIAR                     1132
#define IDC_FORWARD                     1133
#define IDC_EMER                        1136
#define IDC_GPOSE                       1150
#define IDC_EJEPOSE                     1151
#define IDC_TRAJPENDANT                 1157
#define IDC_LEERPOSES                   1158
#define IDC_BORRAR                      1159
#define IDC_PoseActual                  1160
#define IDC_GENTRACJ                    1163
#define IDC_PUNTOACTUAL                 1165
#define IDC_PUNTOSMAX                   1166
#define IDC_AGREGAR                     1167
#define IDC_DELETE                      1168
#define IDC_TRAJPRINT                   1171
#define ID_SETROBOT                     1175
#define IDC_SETRTC                      1176
#define IDC_SETTRACE                    1177
#define IDC_POSX                        1181
#define IDC_POSZ                        1182
#define IDC_POSY                        1183
#define IDC_POSXINV                     1184
#define IDC_POSYINV                     1185
#define IDC_POSZINV                     1186
#define IDC_AngAPROXIMACION             1187
#define IDC_eulerROLL                   1187
#define IDC_eulerROLLkine               1188
#define IDC_RTCTIME                     1190
#define IDC_CLOCKTIME                   1192
#define IDC_SETHORA                     1193
#define IDC_SETALARMA                   1194
#define IDC_LLEERHORA                   1196
#define IDC_READALARMA                  1197
#define IDC_CALINVERSA                  1210
#define IDC_MATRIXKINE                  1211
#define IDC_SCBCINPOS                   1212
#define IDC_SCBHOMPOS                   1213
#define IDC_SCBCODOPOS                  1214
#define IDC_CBOXuPASO                   1214
#define IDC_SCBPITCHPOS                 1215
#define IDC_SETROBODATA                 1215
#define IDC_SCBROLLPOS                  1216
#define IDC_CBOXuPASO2                  1216
#define IDC_SCBCINVEL                   1217
#define IDC_CBOXuPASO3                  1217
#define IDC_SCBHOMVEL                   1218
#define IDC_READROBODAT                 1218
#define IDC_SCBCODOVEL                  1219
#define IDC_CBOXuPASO4                  1219
#define IDC_SCBPITCHVEL                 1220
#define IDC_CBOXuPASO5                  1220
#define IDC_SCBROLLVEL                  1221
#define IDC_MESALARMA                   1221
#define IDC_SCBCINACE                   1222
#define IDC_DIAALARMA                   1222
#define IDC_SCBHOMACE                   1223
#define IDC_MESTIME                     1223
#define IDC_SCBCODOACE                  1224
#define IDC_DIATIME                     1224
#define IDC_SCBPITCHACE                 1225
#define IDC_SCBROLLACE                  1226
#define IDC_YEARTIME                    1226
#define IDC_TIMEAM                      1227
#define IDC_MATRIXINVKINE               1227
#define IDC_TIMEPM                      1228
#define IDC_CALDIRECTA                  1228
#define IDC_DIASEMANA                   1229
#define IDC_CBOXPOT                     1236
#define IDC_CBOXPOT2                    1243
#define IDC_CBOXPOT3                    1252
#define IDC_CBOXPOT4                    1261
#define IDC_CBOXPOT5                    1270
#define IDC_EJEMUESTRA                  1271
#define IDC_SWTENABLE1                  1280
#define IDC_ENCODER_EN1                 1281
#define IDC_SWTENABLE2                  1282
#define IDC_ENCODER_EN2                 1283
#define IDC_SWTENABLE3                  1284
#define IDC_SWTENABLE4                  1285
#define IDC_ENCODER_EN3                 1286
#define IDC_ENCODER_EN4                 1287
#define IDC_SWTENABLE5                  1288
#define IDC_ENCODER_EN5                 1289
#define IDC_CBOXERROR                   1290
#define IDC_CBOXTRACKWIN                1291
#define IDC_CBOXSETTLEW                 1292
#define IDC_CBOXSETTLET                 1293
#define IDC_PMALARMA                    1294
#define IDC_CBOXERROR2                  1294
#define IDC_AMALARMA                    1295
#define IDC_CBOXTRACKWIN2               1295
#define IDC_CBOXSETTLEW2                1296
#define IDC_CBOXSETTLET2                1297
#define IDC_CBOXERROR3                  1298
#define IDC_CBOXTRACKWIN3               1299
#define IDC_CBOXSETTLEW3                1300
#define IDC_CBOXSETTLET3                1301
#define IDC_CBOXERROR4                  1302
#define IDC_CBOXTRACKWIN4               1303
#define IDC_PMDTrace1                   1303
#define IDC_CBOXSETTLEW4                1304
#define IDC_PMDTrace2                   1304
#define IDC_CBOXSETTLET4                1305
#define IDC_PMDTrace3                   1305
#define IDC_CBOXERROR5                  1306
#define IDC_PMDTrace4                   1306
#define IDC_CBOXTRACKWIN5               1307
#define IDC_PMDTrace5                   1307
#define IDC_CBOXSETTLEW5                1308
#define IDC_PMDT1                       1308
#define IDC_CBOXSETTLET5                1309
#define IDC_PMDT2                       1309
#define IDC_PMDT3                       1310
#define IDC_PMDT4                       1311
#define IDC_AXISTRACE                   1312
#define IDC_CONFIGURARTRACE             1313
#define IDC_MAKEBUFFER                  1314
#define IDC_AXISTRACE2                  1315
#define IDC_AXISTRACE3                  1316
#define IDC_AXISTRACE4                  1317
#define IDC_TRACETIME                   1319
#define IDC_PMDT5                       1320
#define IDC_PMDTrace6                   1321
#define IDC_PMDTrace7                   1322
#define IDC_PMDTrace8                   1323
#define IDC_PMDT6                       1325
#define IDC_PMDT7                       1326
#define IDC_PMDT8                       1327
#define IDC_PMDregistro                 1329
#define IDC_TRACETRAJECT                1330
#define IDC_eulerPICH                   1331
#define IDC_eulerPICHkine               1332
#define IDC_MATRIX                      1332
#define IDCANCELMATRIX                  1333
#define ID_CANCELPROGRAMA               1335
#define IDC_COMBOID                     1336
#define IDC_SESCRIBIR                   1338
#define ID_CANCELPOSES                  1339
#define IDC_PIC                         1340
#define ID_EventStatus                  1341
#define ID_AvtivityStatus               1342
#define ID_GetSensor                    1343
#define ID_CommandGetinfomov            1344
#define ID_INICIALIZAR                  40056
#define ID_RESET                        40057
#define ID_TECHBOX                      40058
#define ID_TIPOTRAYECTORIA              40059

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         40060
#define _APS_NEXT_CONTROL_VALUE         1344
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
